service: vulnerable-lambda

provider:
  name: aws
  runtime: python3.8
  region: us-west-2

package:
  individually: true
  include:
    - app.py
    - requirements.txt
  exclude:
    - venv/**
    - node_modules/**

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: app.app
    packRequirements: false  

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
